# Generated by Django 5.1.3 on 2024-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscription_options_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('enterprise', 'Enterprise Plan')], max_length=20),
        ),
    ]
