# Generated by Django 5.1.3 on 2024-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
